config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :sidebar, only: :index
      resources :idols, only: %w[show index]
      resources :blogs, only: %w[show index]
      resources :inquiries, only: :create
    end
  end

  namespace :admin do
    resources :idols
    resources :blogs
    resources :dashboards, only: :index
    mount Sidekiq::Web => "/sidekiq"
  end
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  IMAGE_UPLOAD_LIMIT = 5

  before_save :set_idol_age
  after_save :publish_blogs_count

  mount_uploader :thumbnail, BlogThumbnailUploader
  mount_uploader :piece_image, BlogPieceImageUploader

  acts_as_taggable_on :genres, :sales
  belongs_to :idol
  has_many :content_images, class_name: 'BlogContentImage', foreign_key: :blog_id, inverse_of: :blog
  accepts_nested_attributes_for :content_images, reject_if: :all_blank, allow_destroy: true
  has_many :distributors
  accepts_nested_attributes_for :distributors, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :piece_title, presence: true
  validates :outline, presence: true
  validates :thumbnail, presence: true
  validates :piece_release_on, presence: true
  validate :thumbnail_size
  validate :piece_image_size

  private
  def thumbnail_size
    if thumbnail.size > IMAGE_UPLOAD_LIMIT.megabytes
      errors.add(:thumbnail, "You cannot upload a file greater than #{IMAGE_UPLOAD_LIMIT}MB")
    end
  end

  def piece_image_size
    if piece_image.size > IMAGE_UPLOAD_LIMIT.megabytes
      errors.add(:piece_image, "You cannot upload a file greater than #{IMAGE_UPLOAD_LIMIT}MB")
    end
  end

  def publish_blogs_count
    return unless saved_change_to_attribute?("published")

    idol.update!(publish_blogs_count: idol.blogs.where(published: true).size)
  end

  def set_idol_age
    return unless will_save_change_to_attribute?("piece_release_on")

    self.idol_age = (piece_release_on.strftime('%Y%m%d').to_i - idol.birth_date.strftime('%Y%m%d').to_i) / 10000
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  def index
    @blogs = Blog.all.order(id: :desc)
  end

  def show
    @blog.distributors.build if @blog.distributors.blank?
  end

  def new
    @blog = Blog.new(idol_id: params[:idol_id])
    @blog.content_images.build
    @blog.distributors.build
  end

  def edit
    @blog.distributors.build if @blog.distributors.blank?
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.content_images.build if @blog.content_images.blank?

    if @blog.save
      redirect_to admin_blog_path(@blog), flash: {success: "Blog was successfully created."}
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to admin_blog_path(@blog), flash: {success: "Blog was successfully updated."}
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog.destroy
    redirect_to admin_blogs_url, flash: {success: "Blog was successfully destroyed."}
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(
        :idol_id,
        :title,
        :piece_title,
        :piece_release_on,
        :outline,
        :thumbnail,
        :thumbnail_cache,
        :piece_image,
        :piece_image_cache,
        :genre_list,
        :sale_list,
        :published,
        {content_images_attributes: [:id, :image, :image_cache, :comment, :_destroy]},
        {distributors_attributes: [:id, :name, :url, :_destroy]}
      )
    end
end

app/controllers/api/v1/blogs_controller.rb
require 'pagy/extras/metadata'
module Api
  module V1
    class BlogsController < ApiController
      before_action :set_blogs, only: %i[index show]
      before_action :set_blog, only: %i[show]

      def index
        blogs = params[:tag].blank? ? @blogs : @blogs.tagged_with(params[:tag])
        pagy, blogs = pagy(blogs, page: params[[:page]])
        serialized_blogs = ActiveModelSerializers::SerializableResource.new(blogs, each_serializer: Api::V1::BlogSerializer)
        render json: {
          blogs: serialized_blogs,
          pagination: {
            currentPage: pagy.page,
            totalCount: pagy.count,
            totalPages: pagy.pages,
          }
        }
      end

      def show
        render json: @blog, serializer: Api::V1::BlogSerializer
      end

      private
      def set_blogs
        @blogs = Blog.where(published: true).all.order(id: :desc)
      end

      def set_blog
        @blog = @blogs.find(params[:id])
      end
    end
  end
end

app/views/admin/blogs/_content_image_fields.html.erb
<div class='nested-fields col-sm-6 col-md-4'>
  <% content_image = f.object %>

  <div class="mb-3">
    <%= f.label :image do %>
      <%= tag.div class: 'preview_wrap' do %>
        <%= image_tag content_image.image.thumb.url, class: 'img-fluid preview', style: "#{disabled ? 'pointer-events: none;' : ''}", width: 400, height: 225 %>
      <% end %>
      <%= f.file_field :image, class: 'form-control preview_form', style: 'display:none', disabled: disabled, 'data-default-url' => content_image.image.default_url %>
      <%= f.hidden_field :image_cache %>
      <%= tag.span content_image.image.identifier || 'No Image', class: 'text-secondary preview_filename' %>
    <% end %>
  </div>

  <div class="field mb-3">
    <%= f.text_area :comment, class: 'form-control', rows: 5 , disabled: disabled %>
  </div>
  <% if !disabled %>
    <%= link_to_remove_association "Delete", f, class: "btn btn-danger mx-2 px-4" %>
  <% end %>
</div>

app/views/admin/blogs/_distributor_fields.html.erb
<div class='nested-fields col-sm-6 col-md-4'>
  <div class="field">
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', disabled: disabled %>
    </div>
    <div class="mb-3">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', disabled: disabled %>
    </div>
  </div>
  <% if !disabled %>
    <%= link_to_remove_association "Delete", f, class: "btn btn-danger mx-2 px-4" %>
  <% end %>
</div>

app/views/admin/blogs/_form.html.erb
<%= form_with(model: [:admin, blog]) do |f| %>
  <% if blog.errors.any? %>
    <div class="card mb-3 exception-card">
      <div class="card-body">
        <ul class='m-0 p-0'>
          <% blog.errors.each do |error| %>
            <li class="list-unstyled"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :idol_id, class: 'form-label fs-5' %>
    <%= f.collection_select :idol_id, Idol.all, :id, :name, {prompt: "選択してください"}, {class: 'form-select', disabled: disabled} %>
  </div>
  <div class="mb-3">
    <%= render 'tags', {f: f, context: 'genre', bg_color: 'primary', disabled: disabled} %>
  </div>
  <div class="mb-3">
    <%= render 'tags', {f: f, context: 'sale', bg_color: 'secondary', disabled: disabled} %>
  </div>
  <div class="mb-3">
    <%= f.label :title, class: 'form-label fs-5' %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'ブログのタイトル', disabled: disabled %>
  </div>
  <div class="mb-3">
    <%= tag.label 'Thumbnail', class: "form-label fs-5", style: "display:block;" %>
    <%= f.label :thumbnail do %>
      <%= tag.div class: 'preview_wrap' do %>
        <%= image_tag blog.thumbnail.thumb.url, class: 'preview', style: "#{disabled ? 'pointer-events: none;' : ''}", width: 800, height: 450 %>
      <% end %>
      <%= f.file_field :thumbnail, class: 'form-control preview_form', style: 'display:none', disabled: disabled, 'data-default-url' => blog.thumbnail.default_url %>
      <%= f.hidden_field :thumbnail_cache %>
      <%= tag.span blog.thumbnail.identifier || 'No Image', class: 'text-secondary preview_filename' %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= tag.label 'Piece Image', class: "form-label fs-5", style: "display:block;" %>
    <%= f.label :piece_image do %>
      <%= tag.div class: 'preview_wrap' do %>
        <%= image_tag blog.piece_image.thumb.url, class: 'preview', style: "#{disabled ? 'pointer-events: none;' : ''}", width: 800, height: 450 %>
      <% end %>
      <%= f.file_field :piece_image, class: 'form-control preview_form', style: 'display:none', disabled: disabled, 'data-default-url' => blog.piece_image.default_url %>
      <%= f.hidden_field :thumbnail_cache %>
      <%= tag.span blog.piece_image.identifier || 'No Image', class: 'text-secondary preview_filename' %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label :piece_title, class: 'form-label fs-5' %>
    <%= f.text_field :piece_title, class: 'form-control', placeholder: 'DVDのタイトル', disabled: disabled  %>
  </div>
  <div class="mb-3">
    <%= f.label :piece_release_on, class: 'form-label fs-5' %>
    <%= f.date_field :piece_release_on, class: 'form-control', disabled: disabled  %>
  </div>
  <div class="mb-3">
    <%= f.label :outline, class: 'form-label fs-5' %>
    <%= f.text_area :outline, class: 'form-control', placeholder: '概要', rows: 10 , disabled: disabled %>
  </div>
  <div class="mb-3">
    <%= tag.label 'Content images', class: "form-label fs-5" %>
    <div id='content_images', class="row">
      <%= f.fields_for :content_images do |content_image| %>
        <%= render 'content_image_fields', {f: content_image, disabled: disabled} %>
      <% end %>
      <% if !disabled %>
        <div class='links my-3'>
          <%= link_to_add_association 'Add', f, :content_images, class: 'btn btn-primary mx-2 px-4', render_options: {locals: {disabled: disabled}} %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= tag.label 'Distributors', class: "form-label fs-5" %>
    <div id='distributors', class="row">
      <%= f.fields_for :distributors do |distributor| %>
        <%= render 'distributor_fields', {f: distributor, disabled: disabled} %>
      <% end %>
      <% if !disabled %>
        <div class='links my-3'>
          <%= link_to_add_association 'Add', f, :distributors, class: 'btn btn-primary mx-2 px-4', render_options: {locals: {disabled: disabled}} %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= tag.label 'Published?', class: "form-label fs-5" %>
    <div style="display:block;">
      <%= f.collection_radio_buttons :published, [[true, 'publish'], [false, 'unpublish']], :first, :last do |b| %>
        <%= b.label(class: 'form-check-label') { b.radio_button(class: 'form-check-input', disabled: disabled) + b.text } %>
      <% end %>
    <div>
  </div>

  <div class="my-5">
    <%= f.submit nil, class: 'btn btn-primary mx-2 px-4' if !disabled %>
    <% if action_name == 'show' %>
      <%= link_to 'Edit', edit_admin_blog_path(blog), class: 'btn btn-primary mx-2 px-4' %>
      <%= link_to 'Delete', admin_blog_path(blog), method: :delete, class: 'btn btn-outline-danger mx-2 px-4', data: {confirm: 'Are you sure?'} %>
    <% end %>
    <%= link_to 'Back', back_url, class: 'btn btn-secondary mx-2 px-4' %>
  </div>
<% end %>

app/views/admin/blogs/_tags.html.erb
<% blog = f.object %>
<% tag_list = context + '_list' %>
<% if action_name == 'show' %>
  <%= tag.label "#{context.capitalize} list", class: "form-label fs-5" %>
  <%= tag.div do %>
    <% blog.tag_counts_on("#{context.pluralize.to_sym}").each do |tag_object| %>
      <%= tag.span tag_object.name, class: "badge rounded-pill bg-#{bg_color} fs-6 px-3 py-2 fw-normal" %>
    <% end %>
  <% end %>
<% else %>
  <%= f.label "#{tag_list.to_sym}", class: 'form-label fs-5' %>
  <%= f.text_field "#{tag_list.to_sym}", value: blog.send("#{tag_list}").join(','), class: "form-control", disabled: disabled %>
<% end %>

app/views/admin/blogs/edit.html.erb
<h4>Edit Blog</h4>

<%= render 'form', blog: @blog, disabled: false, back_url: admin_blog_path(@blog) %>

app/views/admin/blogs/index.html.erb
<h4>Blogs</h4>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col" width="260">thumbnail</th>
      <th scope="col">Piece Title</th>
      <th scope="col">Outline</th>
      <th scope="col">Published</th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <%= tag.tr "data-href" => admin_blog_path(blog), class: 'table_item' do %>
        <%= tag.th blog.id, scope: "row" %>
        <%= tag.td blog.title %>
        <%= tag.td do %>
          <%= image_tag blog.thumbnail.thumb.url, class: 'img-fluid' %>
        <% end %>
        <%= tag.td blog.piece_title %>
        <%= tag.td blog.outline %>
        <%= tag.td blog.published ? 'Publish' : 'Unpublish', class: "#{blog.published ? 'text-primary' : 'text-danger'}" %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Blog', new_admin_blog_path, class: 'btn btn-primary' %>

app/views/admin/blogs/new.html.erb
<h4>Add Blog</h4>

<%= render 'form', blog: @blog, disabled: false, back_url: admin_blogs_path %>

app/views/admin/blogs/show.html.erb
<h4>Detail Blog</h4>

<%= render 'form', blog: @blog, disabled: true, back_url: admin_blogs_path %>