config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :sidebar, only: :index
      resources :idols, only: %w[show index]
      resources :blogs, only: %w[show index]
      resources :inquiries, only: :create
    end
  end

  namespace :admin do
    resources :idols
    resources :blogs
    resources :dashboards, only: :index
    mount Sidekiq::Web => "/sidekiq"
  end
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= tag.div class: "alert-#{key} alert alert-dismissible fade show", role: 'alert' do %>
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= button_tag type: 'button', id: 'sidebar_collapse', class: 'navbar-btn' do %>
        <span></span>
        <span></span>
        <span></span>
      <% end %>
    </div>

    <div>
      title now
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
    <h4>Blogs Management</h4>
  </div>

  <ul class="list-unstyled components">
    <li>
      <%= link_to 'DashBoard', admin_dashboards_path %>
    </li>
    <li>
      <%= link_to 'Idols', admin_idols_path %>
    </li>
    <li>
      <%= link_to 'Blogs', admin_blogs_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'module', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag javascript_path, 'data-turbolinks-track': 'reload' if javascript_file_exist?(javascript_path)%>
  </head>

  <body>
    <div class="wrapper">
      <!-- Sidebar Holder -->
      <%= render 'layouts/sidebar' %>

      <div id="content">
        <!-- Page Content Holder -->
        <%= render 'layouts/navbar' %>

        <!-- Page Content Main -->
        <%= tag.div id: 'main-content' do %>
          <%= render 'layouts/flash' %>
          <%= yield %>
        <% end %>
      </div>
    </div>
  </body>
</html>