config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :sidebar, only: :index
      resources :idols, only: %w[show index]
      resources :blogs, only: %w[show index]
      resources :inquiries, only: :create
    end
  end

  namespace :admin do
    resources :idols
    resources :blogs
    resources :dashboards, only: :index
    mount Sidekiq::Web => "/sidekiq"
  end
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/idol.rb
class Idol < ApplicationRecord
  IMAGE_UPLOAD_LIMIT = 5

  mount_uploader :image, IdolImageUploader

  has_many :blogs

  validates :name, presence: true
  validates :birth_date, presence: true
  validates :comment, presence: true
  validates :image, presence: true
  validate :image_size

  before_save :set_calculate_age, if: -> {will_save_change_to_attribute?("birth_date")}

  scope :having_blogs, -> {
    Idol.joins(:blogs).distinct
  }

  def set_calculate_age
    return if birth_date.blank?
    self.age = (Date.today.strftime('%Y%m%d').to_i - birth_date.strftime('%Y%m%d').to_i) / 10000
  end

  def update_age
    set_calculate_age
    save!
  end

  def image_size
    if image.size > IMAGE_UPLOAD_LIMIT.megabytes
      errors.add(:image, "You cannot upload a file greater than #{IMAGE_UPLOAD_LIMIT}MB")
    end
  end
end

app/controllers/admin/idols_controller.rb
class Admin::IdolsController < ApplicationController
  before_action :set_idol, only: %i[ show edit update destroy ]

  def index
    @idols = Idol.all.order(id: :desc)
  end

  def show
  end

  def new
    @idol = Idol.new
  end

  def edit
  end

  def create
    @idol = Idol.new(idol_params)
    @idol.set_calculate_age

    if @idol.save
      redirect_to admin_idol_path(@idol), flash: {success: "Idol was successfully created."}
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @idol.update(idol_params)
      redirect_to admin_idol_path(@idol), flash: {success: "Idol was successfully updated."}
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @idol.destroy
    redirect_to admin_idols_url, flash: {success: "Idol was successfully destroyed."}
  end

  private
    def set_idol
      @idol = Idol.find(params[:id])
    end

    def idol_params
      params.require(:idol).permit(:name, :birth_date, :comment, :image, :image_cache)
    end
end

app/controllers/api/v1/idols_controller.rb
module Api
  module V1
    class IdolsController < ApiController
      before_action :set_idols, only: %i[index show]

      def index
        idols = @idols.all
        render json: idols, each_serializer: Api::V1::IdolSerializer
      end

      def show
        idol = @idols.find(params[:id])
        render json: idol, serializer: Api::V1::IdolSerializer
      end

      private

      def set_idols
        @idols = Idol.having_blogs
      end
    end
  end
end

app/views/admin/idols/_form.html.erb
<%= form_with(model: [:admin, idol]) do |f| %>
  <% if idol.errors.any? %>
    <div class="card mb-3 exception-card">
      <div class="card-body">
        <ul class='m-0 p-0'>
          <% idol.errors.each do |error| %>
            <li class="list-unstyled"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: '名前', disabled: disabled %>
  </div>
  <div class="mb-3">
    <%= tag.p 'image', class: "text-reset mb-2" %>
    <%= f.label :image do %>
      <%= tag.div class: 'preview_wrap' do %>
        <%= image_tag idol.image.thumb.url, class: 'preview', style: "#{disabled ? 'pointer-events: none;' : ''}", width: 150, height: 150 %>
      <% end %>
      <%= f.file_field :image, class: 'form-control preview_form', style: 'display:none', disabled: disabled, 'data-default-url' => idol.image.default_url %>
      <%= f.hidden_field :image_cache %>
      <%= tag.span idol.image.identifier || 'No Image', class: 'text-secondary preview_filename' %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= f.label :birth_date, class: 'form-label' %>
    <%= f.date_field :birth_date, class: 'form-control', disabled: disabled  %>
  </div>
  <div class="mb-3">
    <%= f.label :comment, class: 'form-label' %>
    <%= f.text_area :comment, class: 'form-control', placeholder: 'コメント', rows: 10, disabled: disabled %>
  </div>
  <div class="my-5">
    <%= f.submit nil, class: 'btn btn-primary mx-2 px-4' if !disabled %>
    <% if action_name == 'show' %>
      <%= link_to 'Edit', edit_admin_idol_path(idol), class: 'btn btn-primary mx-2 px-4' %>
      <%= link_to 'Create Blog', new_admin_blog_path(idol_id: idol.id), class: 'btn btn-primary mx-2 px-4' %>
      <%= link_to 'Delete', admin_idol_path(idol), method: :delete, class: 'btn btn-outline-danger mx-2 px-4', data: {confirm: 'Are you sure?'} %>
    <% end %>
    <%= link_to 'Back', back_url, class: 'btn btn-secondary mx-2 px-4' %>
  </div>
<% end %>

app/views/admin/idols/edit.html.erb
<h4>Edit Idol</h4>

<%= render 'form', idol: @idol, disabled: false, back_url: admin_idol_path(@idol) %>

app/views/admin/idols/index.html.erb
<h4>Idols</h4>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col" >Name</th>
      <th scope="col" width="260">Image</th>
      <th scope="col">Birth Date</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @idols.each do |idol| %>
      <%= tag.tr "data-href" => admin_idol_path(idol), class: 'table_item' do %>
        <%= tag.th idol.id, scope: "row" %>
        <%= tag.td idol.name %>
        <%= tag.td do %>
          <%= image_tag idol.image.thumb.url, class: 'img-fluid' %>
        <% end %>
        <%= tag.td idol.birth_date %>
        <%= tag.td idol.comment %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Idol', new_admin_idol_path, class: 'btn btn-primary' %>

app/views/admin/idols/new.html.erb
<h4>Add Idol</h4>

<%= render 'form', idol: @idol, disabled: false, back_url: admin_idols_path %>

app/views/admin/idols/show.html.erb
<h4>Detail Idol</h4>

<%= render 'form', idol: @idol, disabled: true, back_url: admin_idols_path %>